/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Business.Contractor;


public class Contractor {
 
    private String ngoName;
    private String ngoId;
    private static int count;
    //NGO constructor to autogenerated ids
    public Contractor() {
        
        ngoId="ORG"+(++count);
        
    }
    
    
}